const texts = {
  VALIDATING_API_KEY_PAIR: 'Validating API key and secret key',
  SETTING_HAS_BEEN_SAVED: 'Setting is valid and has been saved successfully',
  ORDER_FILLED: 'Order list $1 on $2 has been filled / cancelled.',
  PLACE_ORDER_LABEL: 'Place Order',
  PLACING_ORDER_LABEL: 'Placing Order$1',
  SYMBOL_DOESNT_MATCH: 'Symbol does not match',
  CALLBACK_NOT_FOUND: 'Callback not found',
  NOT_VALID_JSON_FILE: 'Not a valid JSON file',
  ATR_CANNOT_BE_FOUND: 'ATR Indicator cannot be found',
  LAST_BAR_NOT_EXIST: 'Last bar does not exist',
  GET_ATR_ERR: 'Error when getting ATR',
  NO_CREDENTIAL_FOUND: 'No credential found',
  SYMBOL_NOT_FOUND: 'Symbol not found',
  INVALID_API_KEY_AND_SECRET: 'Invalid API key and secret key',
  STOP_LIMIT_ORDER_NOT_EXIST: 'Stop limit order does not exist',
  ORDER_LIST_ID_NOT_EXIST: 'Order ID does not exist',
  CANCELLING_OCO_ORDER_FAILED: 'Failed when cancelling OCO order',
  MARKET_ORDER_NOT_EXIST: 'Market order does not exist',
  SELLING_TO_MARKET: 'Selling asset on market price',
  SOLD_TO_MARKET: 'Asset sold succesfully on market price',
  FAILED_SELL_TO_MARKET: 'Asset failed to sell on market price',
  WEBSOCKET_CLOSED: 'Websocket has been closed',
  UNKNOWN_KEY: 'Config key $1 is unknown and not supported',
  MISSING_KEY: 'Config key $1 is required. Please add it to the config file',
  INVALID_FORMAT: 'Invalid format for config key $1. The correct format is $2',
  VALIDATING_LICENSE_KEY: 'Validating license key',
  LICENSE_KEY_NOT_VALID: 'License key is not valid',
  MACHINE_ID_IN_LICENSE_KEY_IS_INVALID:
    'Machine ID in the license key is invalid',
  UPDATE_AVAILABLE: 'New update is available and will be downloaded shortly',
  UPDATE_DOWNLOADED: 'New update has been downloaded. Restart to install it.',
  RESET_SUCCESS: 'The app has been restored like a new born',
  RESET_INDICATOR_SUCCESS: 'All indicators has been restored to default',
  UPDATE_ERROR: 'Error when updating the app',
  CHECKING_FOR_UPDATE: 'Checking for update',
  ERROR_GETTING_SYMBOL_LISTS: 'Error when getting list of symbols',
  SKIPPED_BECAUSE_SYMBOL_LIST_NOT_EMPTY:
    'Skipped fetching symbol list because it is not empty',
  STOP_LOSS_RATIO_CANNOT_BE_EMPTY: 'Stop loss ratio field cannot be empty',
  STOP_LOSS_RATIO_MUST_BE_NUMBER: 'Stop loss ratio must be a number',
  TAKE_PROFIT_RATIO_CANNOT_BE_EMPTY: 'Take profit ratio field cannot be empty',
  TAKE_PROFIT_RATIO_MUST_BE_NUMBER: 'Take profit ratio must be a number',
  REST_API_BASE_URL_CANNOT_BE_EMPTY: 'REST API base URL field cannot be empty',
  WEBSOCKET_BASE_URL_CANNOT_BE_EMPTY:
    'Websocket base URL field cannot be empty',
  API_KEY_CANNOT_BE_EMPTY: 'API key field cannot be empty',
  SECRET_KEY_CANNOT_BE_EMPTY: 'Secret key field cannot be empty',
  STOP_LIMIT_FILLED: 'Stop limit order has filled',
  STOP_LIMIT_FILLED_TEXT: 'Your stop limit order on $1 has been filled.',
  STOP_LIMIT_PARTIALLY_FILLED: 'Stop limit order has partially filled',
  STOP_LIMIT_PARTIALLY_FILLED_TEXT:
    'Your stop limit order on $1 has been partially filled.',
  TAKE_PROFIT_FILLED: 'Take profit order has filled',
  TAKE_PROFIT_FILLED_TEXT: 'Your take profit order on $1 has been filled.',
  TAKE_PROFIT_PARTIALLY_FILLED: 'Take profit order has partially filled',
  TAKE_PROFIT_PARTIALLY_FILLED_TEXT:
    'Your take profit order on $1 has been partially filled.',
  BINANCE_SETTING_NOT_SET_YET: "Binance setting hasn't set yet",
  TOOK_PROFIT: 'Profit taken',
  STOP_LIMIT: 'Stop limit',
  SOLD: 'Sold',
  NO_SYMBOL_FOUND: 'No symbol found',
};

export default texts;
